### ISSUE TITLE
More lightweight releases

### ISSUE THREAD

**Issue by Daryes** [ansible-collections/overview#177]
##### SUMMARY
Hello,
I hope I'm in the right repo for an issue with ansible releases.

This said, not to be nitpicking, but when installing the metapackage ansible 3.4.0, I was surprised by the size the docker image took.

Create a virtualenv and install ansible with  `pip3 install --no-cache-dir ansible==3.4.0`
Then :
```
$ cd <venv>
$ du -sh 
484M    .

$ cd lib/python3.*/site-packages/ansible_collections
$ du -sh
400M    .

# list all "tests" directories under collections and return their disk size
$ find . -name "tests" -type d -print0 | xargs -0 du -sh --total
(...)
122M    total
```
That was at first glance. 

While I understand the need of the unit and integration tests, they can become heavy in disk space consumption.
Maybe I missed something, but is there a requirement to have them shipped in the release build ?

##### ISSUE TYPE
- Enhancement

**Comment by tadeboro** [comment]
We talked about this topic a lot in community meetings. Still, we never got the definitive answer if we can legally drop test files from the PyPI artifact or create a separate package with only test files.

The `ansible` package maintainers do not maintain all of the collections included in it. They download the latest stable and semver-compatible versions from Ansible Galaxy and add them to the build. If we go and strip the tests from the collection, we are actually modifying the artifact collection maintainer uploaded to Galaxy. And this is the main reason we are not sure if we can safely drop the tests from the final artifact.

Would you be so kind and open a new issue with the same content in the https://github.com/ansible-community/community-topics repo (this is where community members keep all the things we need to discuss) so that it does not get lost? I would ask someone to move the issue, but IIRC, GitHub does not allow moving issues between different organizations.

**Comment by Daryes** [comment]
Issue created in community-topics.  
Feel free to close this one if required.

**Comment by felixfontein** [comment]
Thanks for creating the issue! I'll close this one since this isn't the best place :)
