### ISSUE TITLE
Clarifications about claiming existing module in community.general/creating new collection

### ISSUE THREAD

**Issue by SHxKM** [ansible-collections/overview#178]
Hi,

My company has a module in `community.general` that I guess was moved there after Ansible Classic. Since then, our own Ansible repo and the code under the module are completely detached. We'd like to change that.

The FAQ states that the way to go for most organizations is creating an independent collection. However, some things are still unclear to me:

1. In the `community.general` README it's written that `community.general` comes included when one installs Ansible package:
    > This repository contains the community.general Ansible Collection. **The collection is a part of the Ansible package** and includes many modules and plugins supported by Ansible community which are not part of more specialized community collections.
    
    And the FAQ in this repository states that ansible (the package) is:
    
    > A replacement software package (Python, deb, rpm, etc) which contains a select group of Collections. It contains the collections to ensure that Ansible 2.9 playbooks don't require any extra collections to be be installed. This list of what's included can be found at ansible-build-data. Will depend on the ansible-base package. Was previously referred to as ACD (Ansible Community Distribution).

    And in the same page this is what is written about Ansible Classic:

    > What we think of as Ansible prior to 2020. The open source project and the deliverable. **What you currently get (as of Ansible 2.9 and earlier versions) when you type pip install ansible**. Was developed almost entirely within the ansible/ansible repository on GitHub.

    Am I right to assume that as of today, when someone runs `pip install ansible` they get a version that is > `2.9` (I already confirmed that) that contains no collections at all (including `community.general`)? And therefore the only way to get ansible with the `community.general` collection installed is to `pip install ansible==2.9`?

2. Assuming we want to go the separate collection route, who actually manages (read: has write access) to the repository at `https://github.com/ansible-collections/mycompanysnamespace.some_collection`? Because Ansible clearly owns the repository itself.

3. Follow up on question 2: is it possible/advisable to have a workflow where code is maintained in a separate repository (owned by my company) and changes/fixes are synced with the repository which is under `ansible-collections`?

Thanks in advance

**Comment by tadeboro** [comment]
>        Am I right to assume that as of today, when someone runs `pip install ansible` they get a version that is > `2.9` (I already confirmed that) that contains no collections at all (including `community.general`)? And therefore the only way to get ansible with the `community.general` collection installed is to `pip install ansible==2.9`?

No. When you run `pip install ansible` today, you will get `ansible-core` Python package + a lot of Ansible collections that contain the content that was part of Ansible 2.9. `community.general` is one such collection, but there are plenty more. All of them are listed at https://docs.ansible.com/ansible/latest/collections/

>     2. Assuming we want to go the separate collection route, who actually manages (read: has write access) to the repository at `https://github.com/ansible-collections/mycompanysnamespace.some_collection`? Because Ansible clearly owns the repository itself.

You do not have to host your collection in the ansible-collections GitHub organization. It is perfectly valid to host it under your own organization and have that collection included in the `ansible` Python package. For example, the Sensu Go Ansible Collection is hosted at https://github.com/sensu/sensu-go-ansible and is still part of the `ansible` Python package. If you want to have your collection included in Ansible, you just need to follow the rules from https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst and then ask for your collection to be included at https://github.com/ansible-collections/ansible-inclusion.

>     3. Follow up on question 2: is it possible/advisable to have a workflow where code is maintained in a separate repository (owned by my company) and changes/fixes are synced with the repository which is under `ansible-collections`?

No need to sync things since you can host the code anywhere.

**Comment by SHxKM** [comment]
@tadeboro Thanks a lot of the quick reply and clarifications. So if I understand right, there's currently no upside for keeping our module in `community.general` / downside in developing our own collection and have it included in the Python package?

**Comment by tadeboro** [comment]
Well, if you keep the modules in the existing collection, at least the CI/CD parts of the management are taken care of for you. But if you do not have an issue maintaining that yourself, then there is really no downside of moving the content into a separate collection.

Do note that you and/or your team will have to "prove" yourself before your new collection can replace the current content. Getting your collection included in the Ansible package is one thing (this is quite easy if you follow the best practices when developing content), serving as a replacement for some content is a bit more nuanced since there are (probably) existing users that rely on the content.

**Comment by SHxKM** [comment]
> Well, if you keep the modules in the existing collection, at least the CI/CD parts of the management are taken care of for you.

Thanks @tadeboro. I assume this is referring to running the different test suites, etc...and deploying to Galaxy?

**Comment by tadeboro** [comment]
> > Well, if you keep the modules in the existing collection, at least the CI/CD parts of the management are taken care of for you.
> 
> Thanks @tadeboro. I assume this is referring to running the different test suites, etc...and deploying to Galaxy?

Yes. Community-maintained collections have things like AZP already set up (and sponsored by Red Hat actually), so by working on the content in one of the existing collections, you do not have to maintain such things yourself and can focus on content development.

**Comment by felixfontein** [comment]
Most community collections are using GitHub Actions, though. AZP is only used for very few collections.

**Comment by SHxKM** [comment]
@tadeboro @felixfontein - thanks both. One last question: if I release a minor version of my (future) collection, are changes reflected in Ansible package immediately? some insight into how this works would be much appreciated.

**Comment by tadeboro** [comment]
Ansible package is released once every three weeks. If you release a new patch or minor release, your users will only receive it when the next minor version of Ansible is released.

**Comment by SHxKM** [comment]
But is it correct that if they choose to install the collection from Galaxy they will get the changes immediately?

**Comment by SHxKM** [comment]
Many thanks gentlemen @tadeboro @felixfontein
