### ISSUE TITLE
[?w] changelog process for collections

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#18]
* How do we notify users of (potentially) breaking changes (aka porting_guide)
* How do we notify users of new features?
* Do we need to document bug fixes

Once we've answered the above, we can look at tooling that exists.

**Comment by samccann** [comment]
# Release Note / Changelog Fragment Ideas for Collections

We have a continuing need for changelogs (or release notes) to cover:

* ansible/ansible - currently has a working solution using changelog fragments
* collections - two options mentioned so far are [reno](https://docs.openstack.org/reno/latest/) and [towncrier](https://pypi.org/project/towncrier/)
* Ansible Community Distribution (ACD) - a bundled package that includes the trimmed down ansible/ansible and a set of curated collections that will mimic the current user experience of Ansible with all batteries included (2.9 level of content). ACD has no proposed solution yet, but whatever is used by collections has to provide fragments that can be drawn up into an ACD changelog/release note.

## Reviewing similar projects

We've looked at how RHEL, Fedora, and OpenStack handle this scenario. These projects are built from a subset of projects/components that are similar to how ACD will be created.

### RHEL

RHEL is a release that combines a set of subprojects (e.g. gnome, linux kernel, qemu, etc). Looking at hte RHEL release, it includes Release Notes and Red Hat Errata.  The Release Note focuses on new features, bug fixes, and known issues since the last RHEL release. It does not include a combined list of changelogs etc from all the subprojects upstream that make up RHEL.  The errata is a more detailed list of bugfixes and upstream subprojects included in the RHEL release, but again, does not include details on all the changes that happened in all the subprojects.  RHEL uses internal tools the generate the release notes and errata.

### Fedora

Fedora is upstream of RHEL and is also built from a set of upstream subprojects. Fedora includes [release notes](https://docs.fedoraproject.org/en-US/fedora/f31/release-notes/index.html) and  [ChangeSet](https://fedoraproject.org/wiki/Releases/31/ChangeSet). One package example (RPM) shows a link to the upstream release notes that are a summary of changes from one major release to another (e.g. RPM 4.14x to RPM 4.15.0) That RPM release note appears to be manually created. Since Fedora upgraded from RMP 4.14 to RPM 4.15, the release notes upstream show the full set of changes that were manually added to the release note. Another example, the gnu c library - the Fedora release notes have high-level changes and point to the upstream NEWS section for the gnu c project for details. This news section seems to be partly manually written, and partly a script-generated list of bugfixes.

### OpenStack

Openstack uses the [reno](https://docs.openstack.org/reno/latest/user/usage.html#editing-a-release-note) to create a release note for each individual subproject. There is a main page that lists all the individual projects and links to their release notes. Openstack subprojects appear to only release when Openstack releases so in that sense, they are different from ACD, which is a compilation of collections that may have released multiple times between ACD versions.

**Comment by samccann** [comment]
https://github.com/ansible-collections/kubernetes/issues/40 is also discussing this...

**Comment by samccann** [comment]
# Changelog tool options

This comment summarizes the changelog tools under investigation. All tools must:

- work with git
- provide changelogs or porting_guide to be written in fragments committed with the code change.
- automate  the creation of the changelog summary file for the collection.


## OpenStack reno

The [reno](https://docs.openstack.org/reno/latest/user/index.html) project:

- uses ``yaml`` files stored in a subdirectory (the yaml accepts .rst format inside). These are never removed from the repo.
- installable with ``pip``
- customizable 'sections' - so we might be able to recreate some of our current changelog sections (e.g. new modules, deprecated features, etc)
- includes a section called ``upgrade`` that could be used to pull out just porting-guide like content with a separate script.
- fragment type is determined by the content of the yaml file
- includes a Sphinx extension to allow the release note html file to be generated from the fragments.
- possible [Travis CI integration?](https://docs.openstack.org/reno/latest/user/usage.html#within-travis-ci)
- notes are output in the order they appear in ``git history`` for each section.
- includes a ``reno lint`` option to check the syntax of the fragments to help enforce correctness.
- can configure the ``earliest_version`` that ``reno`` will include within the release note. I think this uses the git release tags.
- [example fragments](https://github.com/openstack/reno/tree/master/releasenotes/notes)
- [example release note](https://docs.openstack.org/reno/latest/releasenotes/index.html)


## towncrier

The [towncrier](https://pypi.org/project/towncrier/) project:

- uses ``rst`` fragment files stored in a subdirectory.
- installed with ``pip``.
- deletes all fragments (git rm) once the news.rst file is generated.
- fragment type seems determined by the fragment filename.
- [example fragments](https://github.com/hawkowl/towncrier/tree/master/src/towncrier/newsfragments)
- [example News.rst output](https://github.com/hawkowl/towncrier/blob/master/NEWS.rst)

**Comment by mattclay** [comment]
We should also consider updating the current changelog tool we use to work with collections. We used `reno` originally, but built our own tool for additional features we needed:

1. Automatically document new plugins and modules. No fragment creation required.
2. Does not require `git` to function.
3. Supports sub-sections in the table of contents and in the details for each released version.
4. Provides linting for both the `yaml` and the embedded `rst` in fragments.

That last one is critical, as it's embedded into `ansible-test sanity` testing (currently only for Ansible), to prevent invalid fragments from being merged. Without that, invalid fragments are not discovered until release time when build failures occur due to invalid syntax.

I'm sure there are other features I'm forgetting as well, but I think I covered most of the major ones.

**Comment by felixfontein** [comment]
I prefer Ansible's tool and towncrier over reno, since they don't enforce a specific git workflow.

Ansible's tool also has the advantage that we can easily adjust it to do exactly what we want. And people working with Ansible really should be familiar with YAML files :)

**Comment by samccann** [comment]
@felixfontein can you clarify the git workflow you are talking about? I think in order for use to be able to gather fragments from multiple collections (and multiple releases within the collection) to get a complete ACD release note, we will need those git release tags within the collections.

**Comment by mattclay** [comment]
@samccann The current tool tracks every fragment that goes into a release in a JSON file, so it's trivial to find out which fragments belong in which release without using `git`.

**Comment by mattclay** [comment]
For those not familiar with the current tool, here's a basic idea of how it works in ansible/ansible:

1. Contributors add changelog fragments in PRs. These are tested with ansible-test before merging. This prevents syntax errors in the yaml and embedded rst, as well as any issues with parsing or generating the release notes at the time of release.

2. When releasing a new version of the code, the changelog tool is executed. It uses a YAML file to keep track of which changelog fragment belongs in which release. This file is committed as part of the release process. This avoids depending on `git` or any other SCM to work with changelog fragments. The file just needs to exist in the source.

3. To generate a human readable changelog, the changelog tool is executed. It reads the YAML file which assigns fragments to releases, as well as the fragments, and generates a readable changelog. 

Since steps two and three are separate, it allows for things like generating a detailed changelog of pre-releases and then collapsing the pre-release entries for a GA release.

This could also be used to facilitate processes such as combining changelog fragments from multiple collections and generating a comprehensive changelog. The original fragments would be used, yet the resulting changelog output could be, if desired, organized and formatted differently.

**Comment by mattclay** [comment]
Step number two is also where the tool creates entries to track new plugins and modules in the YAML file, which is why fragments do not need to be manually created for those. No need to worry about forgetting to document a new plugin or module.

**Comment by resmo** [comment]
Ansible's tool (let's give it a name) because it has all we need and we used it before.

**Comment by felixfontein** [comment]
ansichlog? :)

**Comment by geerlingguy** [comment]
Whatever we choose, I just want it to be simple, and ideally also have some way of linting (if possible) so whoever does releases for collections doesn't have to sit around manually cleaning up stuff at release time. It's already a larger burden pushing out new releases for collections than roles, and would be especially bad if we can start automating releases but those releases get broken due to bad fragments.

**Comment by sshnaidm** [comment]
Will it be a must and be forced for all collections in ACD? In Openstack Ansible Collection we consider to use reno, as it's Openstack native tool for changes.
If Ansible changelog tool will be chosen here, does it mean all others must accept it? Or we still can use whatever we prefer.

**Comment by webknjaz** [comment]
> * uses `rst` fragment files stored in a subdirectory.

Not just RST. It can be any text file and the changelog rendering can be templated w/ jinja2.

**Comment by webknjaz** [comment]
> also have some way of linting

FYI for reno fragments, ansible/ansible does this in CI. For towncrier, I have a GitHub App enforcing the presence of the fragments in PRs.

**Comment by samccann** [comment]
# Changelog Idea Comparison

Goal: provide a unified changelog for ACD

**NOTE:** Current thinking is that the porting guide for ACD would be handled the same as we handle it today for ansible (core) - that is, we provide the shell of a porting guide and each collection owner is responsible for putting in the details necessary for an ACD user to upgrade from the current ACD version to the new ACD version (for their respective collection).


## #1 Require ansible/ansible changelog process

Pros:

- Devs used to it
- Minimal extra coding

Cons:

- Limits collection owner flexibility
- Requires turning ansible/ansible solution into separate package that collection owners can use
- Current implementation works best when old changelog entries are cleared out each time a new stable release branch gets cut; may be tricky if changelog entries stay forever


## #2 Recommend ansible/ansible approach or collection owner must provide changelog file per release in ansible-defined format.

Pros:
- Provides some flexibility for collection owners

Cons:
- requires coding from #1 plus coding to fetch each collection's changelog files
- Collection maintainers would need to transform whatever format they use into the ansible-defined format

## #3 Same as #2 but includes individual changelog fragments

## #4 Link to changelogs within collections

Pros:
- Minimal extra work for ACD dev & collection owners
- Provides most flexibility for collection owners to do what they want with changelogs

Cons:
- Users have to click the links and read each collection changelog separately

## #5 Same as #4 but have a manual release note for ACD that collection owners can add important changes to.

Pros:
- Provides a way for users to see just the important changes vs all changes within a changelog.

Cons:
- Users who want more detail still have to follow all the links for their collections
- Possible duplication between the manual release notes and the manual porting guides

**Comment by felixfontein** [comment]
My peronal ranking (best to worst): 2, 5, 4, 1 (I intentionally left 3 away)

**Comment by pabelanger** [comment]
I'm a big fan of reno. And have wanted to enable it on network collections for some time.

**Comment by danielmellado** [comment]
+1 for reno, it'll be also a straighforward change for network collections/tox

**Comment by jimi-c** [comment]
3, 2, 4, 5, 1 (best to worst).

I always figured it'd be the same way changelogs in RPMs are handled - the changes are in the collection and can be viewed by viewing the collection's information. I prefer #3 to #2 (fragments vs. monolithic).

**Comment by webknjaz** [comment]
I prefer # 2

**Comment by webknjaz** [comment]
@samccann you may want to create a poll via https://github.com/apps/polls next time

**Comment by abadger** [comment]
@pabelanger @danielmellado Note: reno is only sort of an option. #2 would require collection owners to create some code so that reno can output a machine parsable changelog that our tools can then pull in to make a unified changelog/porting guide.  #3 would require the same but at the fragment level instead of a single output file (there would probably need to be an additional metadata file as well that pulled out what fragments belong to which release.).  #4 would let you use reno and you'd manually tell us what the link to your reno-generated changelog is so that we can add the link to our changelog/release notes. #5 Would be the same but docs would merge manual requests from collection owners to highlight things that collection owners considered important enough to show up in the ACD changelog.

**Comment by felixfontein** [comment]
@jimi-c as I understand it, 3 vs. 2 only means whether the fragments have to be there for ACD to consume them. For creating changelogs, I really prefer fragments as well, but I don't mind if collections using other tools provide the compiled changelog as a combined YAML file and not as a set of changelog fragment files.

**Comment by jimi-c** [comment]
@felixfontein sure it can be whatever, just that the end product is a set of fragments (or single file) that we process.

**Comment by abadger** [comment]
My preferences in order are: 2, 5, 4, 3 (leaving out 1).

My rationale closely matches felixfontein's.  The reason I leave out 1 but leave in 3 is that I don't think that limiting the collection owners choices will work (see how people are voting for reno, for instance ;-) so I don't think 1 is viable.  I view 3 as being like 2; collection owners need to write some code so their favorite tool can output a changelog format that we can use.  It's just that the format would be in separate files rather than in a single file.

**Comment by thedoubl3j** [comment]
(best to n/a) 4 -> 2. 
(4)With collections, we gave a lot of stuff over to the creators/maintainers in regards to release cadence and control. I think giving them more flexibility to use what might already be in there ecosystem to manage this is a good idea rather than giving them this tool that only handles ansible specific things. 
(2) But on the flip side, I am also not against rocking the boat and changing things "because change". I also think we are early enough into this (naive, yes I know) in that introducing this would not be a big change for folks but rather just another thing to include.

**Comment by felixfontein** [comment]
@thedoubl3j options 2 and 3 also allow collections to not provide the changelog in the format we want, in which case we'd just link to their changelog. I.e. 4 would be the fallback for 2 and 3 if collections decide they don't want to do the extra work or use our tool.

**Comment by pabelanger** [comment]
@abadger IMO, we are talking about 2 things, release notes and changelog.  for changelog, I'm okay with getting that directly from git commits as they are usually develop focused. And release notes, again reno.  Given that ansible/ansible kinda forked reno, to create changelog fragments, I never quiet understood why not to push up those features upstream.

**Comment by bmbouter** [comment]
In various projects I work in we use towncrier. The audiences for git commits and user changelog entries are different, so having dedicated fragments for the changelog like towncrier uses (to me) is ideal. Also for my personal preferences I think markdown > rst > yaml

**Comment by geerlingguy** [comment]
This issue is getting nice and long, but my input is:

  - markdown > rst > yaml
  - ideally collections can kinda diverge and do what they want, though requiring a changelog of some sort to link to is required for any collection that is linked in Ansible's BOTMETA
    - If we try to make it so ACD is Ansible 2.9 but now Ansible 2.10, and make it like all the collections are part of Ansible, then what was the point of splitting out collections in the first place?
  - Preference order: `#4`, `#2`, then `#3`

I say this as someone who will be helping maintain a collection. Having a recommended method is good, but some collections will wither on the vine (more so than they would due to normal attrition) if we're going to be very strict about the format and requirements, causing the PR review and release process to take up a lot of time for the overhead of maintaining a simple changelog...

If we had a dedicated release manager for each collection then maybe it wouldn't be a burden, but I don't see that happening.

**Comment by jborean93** [comment]
I personally see 4, maybe 5, as the best and really only option, we've already seen that each collection maintainer(s) want to follow their own setup when it comes to things like repo structure, CI, build/release process and I don't see how a changelog will be any different in how it ends up. In a perfect world we could potentially mandate this structure but I've seen so many different processes where I don't think it's possible to make everyone happy.

Potentially the only 2 things we would want to mandate for this scenario would be

* The location, it would be nice for a changelog to be in the same location for each collection in ACD so I know where to look when I want to see the changes specific to a collection
* Potentially the format, we could even be lax and say whatever is auto formatted by GitHub or <insert svc provider>

I don't think the above is necessary but just food for thought.

A side benefit of having just a link to each collections' changelog is that things are grouped by collection so say I was only interested in Windows only improvements I would just go to the 2 Windows collections.

**Comment by Andersson007** [comment]
2

**Comment by resmo** [comment]
My thoughts: The reason ansible would like control the format is to have control in the result presenting changelogs to the user. Basically we would like to show an 2.9 like changelog to the users. That is why I vote for  __2 or 3__.

On the other hand I would like to let the decision to the collection to follow ansible's recommendation and fallback to minimal set of agreement: __just provide a changelog file: 4__

3, 2 with fallback 4

**Comment by jborean93** [comment]
The other part that really throws a spanner in the works is that a collection release is not necessarily tied to an Ansible release so if ACD requires a separate changelog between ACD versions then that's another thing to manage in the changelog.

**Comment by felixfontein** [comment]
@jborean93 that's why I like 2/3, because that would allow to extract the relevant changelogs automatically for how many collection versions there were between two ACD releases.

**Comment by Andersson007** [comment]
2/3

**Comment by samccann** [comment]
# Summary of voting/comments

Based on the comments and actual votes, the top vote-getter is:

**2** - **recommending the ansible/ansible approach** (and the assumption that we'd turn this into a tool that collection owners could use). 
 - The collection owner can also use any tool they want (reno, towncrier, etc), but need to provide a per-collection changelog file that matches the current format of ansible/ansible changelogs. 
-  In the event that the collection owner doesn't provide a properly-formatted file per collection release, we would default to adding a link to their changelog in whatever human-readable format it is in.

**Comment by apple4ever** [comment]
My vote is 5 first, then 4 then 2. 

I much prefer direct linking so I can see just what I want. I don't need a giant list that is hard to scan about changes. Having important changes noted would be nice, but if I don't care about AWS but do care about Azure, I should just be able to dive into their logs.

**Comment by samccann** [comment]
This is a mockup of what an ACD level changelog file might look like - https://github.com/samccann/ansible/blob/test-changelog/docs/docsite/rst/changelog_acd.rst

**Comment by Andersson007** [comment]
BTW
```
- get_certificate - Fix cryptography backend when pyopenssl is unavailable (https://github.com/ansible/ansible/issues/67900)
- openssh_keypair - add logic to avoid breaking password protected keys.
```
Would be good to officially determine a proper changelog message format:
- should it start from uppercase letter or lowercase?
- should it be contain a link to a pr itself if it does not have an issue?
- should it have a dot in the end?
Mix of things like above looks a bit sloppy:)

**Comment by felixfontein** [comment]
I tried to generalize Ansible's changelog generator to collections; here's my current state: https://github.com/felixfontein/ansible-changelog/

I've ran it for community.general (with `version_added: 1.0.0` for all new content); here's the result: https://github.com/felixfontein/community.general/tree/changelog-1.0/changelogs

In particular:
 * the changelog YAML container file: https://github.com/felixfontein/community.general/blob/changelog-1.0/changelogs/changelog.yaml
 * the generated .rst file: https://github.com/felixfontein/community.general/blob/changelog-1.0/changelogs/CHANGELOG-v1.rst

**Comment by samccann** [comment]
reno/towncrier etc users - can you please evaluate the changelog YAML container file in the above comment? That is similar to what we would want collection owners to produce if they don't use the proposed changelog generator based on ansible/ansible.  (with the final fallback of just giving us a link to whatever the collection owner has)

**Comment by felixfontein** [comment]
Here is a code-generated version of @samccann's mockup: https://github.com/felixfontein/ansible-changelog/blob/master/acd/acd.rst

And here another version which has ACD versions as top-level index, and below that sections for Ansible Base and the collections: https://github.com/felixfontein/ansible-changelog/blob/master/acd/acd2.rst

The changelog is parameterized by the following config file: https://github.com/felixfontein/ansible-changelog/blob/master/acd/acd.yml, and generated by https://github.com/felixfontein/ansible-changelog/blob/master/acd/acd.py

**Comment by Andersson007** [comment]
https://github.com/ansible/ansible/pull/69268 , it's a PR about changelog entry's format i mentioned above

**Comment by felixfontein** [comment]
I started writing specification of the `changelog.yaml` format [here](https://github.com/felixfontein/ansible-changelog/blob/master/CHANGELOG-FORMAT.md), and I included a [linter](https://github.com/felixfontein/ansible-changelog/blob/master/ansible_changelog/lint.py) for such files in the ansible-changelog tool.

**Comment by felixfontein** [comment]
I also created a [test collection](https://galaxy.ansible.com/felixfontein/versioning_test_collection) with a changelog spanning multiple `changelog.yaml` files and a non-trivial versioning history.

**Comment by felixfontein** [comment]
ansibulled has been renamed to [antsibull](https://github.com/ansible-community/antsibull/), and [can now be installed via pip](https://pypi.org/project/antsibull/). Part of antsibull is antsibull-changelog, the changelog generator! [Here is some documentation for collection maintainers on using it](https://github.com/ansible-community/antsibull/blob/master/docs/changelogs.rst).

If you are using another changelog generator and want to output a ACD-compatible changelog.yaml file, [the format is documented here](https://github.com/ansible-community/antsibull/blob/master/docs/changelog.yaml-format.md), and antsibull includes a validator (`antsibull-lint changelog-yaml`).

**Comment by felixfontein** [comment]
The changelog generator was moved to https://github.com/ansible-community/antsibull-changelog/ and can be installed via pip (https://pypi.org/project/antsibull-changelog/). The docs are now [here](https://github.com/ansible-community/antsibull-changelog/blob/master/docs/changelogs.rst), and the [changelog.yaml syntax is here](https://github.com/ansible-community/antsibull-changelog/blob/master/docs/changelog.yaml-format.md).

**Comment by felixfontein** [comment]
`ansible-test sanity` now includes a changelog fragment linting sanity check: if `changelogs/fragments/` exists and contains files, these will be linted with antsibull-changelog. (If `changelogs/config.yaml` does not exist when fragments are found, the test will fail.)

**Comment by samccann** [comment]
@felixfontein  - seems like this issue can be resolved now that https://pypi.org/project/antsibull-changelog/ is live?

**Comment by felixfontein** [comment]
@samccann I think so! Thanks for reminding us :)
