### ISSUE TITLE
repo: ibm.csm

### ISSUE THREAD

**Issue by blearandy** [ansible-collections/overview#211]
##### SUMMARY
Collection focusing on the management of IBM storage advanced copy services through the IBM Copy Services Manager product

##### Name of collection
ibm.csm

##### GitHub maintainers
blearandy
dblea0

**Comment by Andersson007** [comment]
hello @blearandy , do you want us to create this repository in the ansible-collections organization?
if yes, an empty one or copied from https://github.com/ansible-collections/collection_template?

**Comment by blearandy** [comment]
Yes. Please create in Ansible-collections org and use the template. Thanks!

**Comment by Andersson007** [comment]
@blearandy done, you both have been invited (please check your mail boxes) with access level:
@blearandy - admin
@dblea0 - maintainer

Could you folks:
- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/[news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)) repo and track announcements there. The ansible-core guys publish changes related to CI (and not only). So if you later set up, say, sanity testing or whatever, you'll be informed in advance about the changes. Otherwise, your CI will get red one day in PRs for unclear reasons.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn).
- Also we have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). Might be useful to take a look.

Thanks

**Comment by Andersson007** [comment]
In addition to the above @blearandy if one day you want to see the collection to the ansible community package, I would recommend to take a look at the [Collection checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md) (it's a short version of the [Collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)). Taking it in consideration at the development stage will potentially make the inclusion process easier for maintainers and reviewers.

**Comment by Andersson007** [comment]
i'll close the issue. If there's a need, feel free to re-open, thanks

**Comment by Andersson007** [comment]
FYI: also added the collection to Zuul auto-publishing on Galaxy via tags, see the [release manual](https://github.com/ansible/community-docs/blob/main/releasing_collections_without_release_branches.rst) for more info on how to release using tags
