### ISSUE TITLE
repo: community.nextcloud

### ISSUE THREAD

**Issue by Spacelord09** [ansible-collections/overview#213]
##### SUMMARY

Collection focusing on modules to deploy and configure nextcloud via Ansible.

##### Name of collection
community.nextcloud

##### GitHub maintainers
@Spacelord09

**Comment by Andersson007** [comment]
@Spacelord09 hello, as I can see https://github.com/ansible-collections/community.nextcloud has already been created by @gundalow.

Could you please:
- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/[news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)) repo and track announcements there. The ansible-core guys publish changes related to CI (and not only). So if you later set up testing, you'll be informed in advance about the changes. Otherwise, your CI will get red one day in PRs for unclear reasons.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn).
- We have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). Might be useful to take a look.
- If one day you want to see the collection to the ansible community package, I would recommend to take a look at the [Collection checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md) (it's a short version of the [Collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)). Taking it in consideration at the development stage will potentially make the inclusion process easier for maintainers and reviewers.
- Share the above with future maintainers.

I'll close the issue. If there are any questions, feel free to ask.
Thanks!

**Comment by Andersson007** [comment]
> Has Zuul been configured?

Good catch, i'll reflect it somewhere:
https://github.com/ansible/zuul-config/pull/426

**Comment by Spacelord09** [comment]
Thanks guys!

Im trying to push some code this weekend.

**Comment by Andersson007** [comment]
@Spacelord09 you're welcome!

As https://github.com/ansible/zuul-config/pull/426 (zuul galaxy auto publishing)  is merged, i'll close the issue
