### ISSUE TITLE
repo: community.sonic

### ISSUE THREAD

**Issue by bluecmd** [ansible-collections/overview#225]
##### SUMMARY

I would like to request the creation of `community.sonic` to start a new Ansible module for the [SONiC](https://sonic-net.github.io/SONiC/) network OS

##### Name of collection

`community.sonic`

##### GitHub maintainers

Initially:

@bluecmd
@fyx
@sonix-tisteagle
@SoundGoof
@Zmegolaz
@robo-kamel

**Comment by Andersson007** [comment]
hello @bluecmd , thanks for requesting the repo, I'll take a look next week

(just a fyi, if you're planning to submit your collection for inclusion in the Ansible package in future, the [Collection requirements](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html) will be useful.)

**Comment by Andersson007** [comment]
@bluecmd 

The [repo](https://github.com/ansible-collections/community.sonic) has been created. The specified logins have been added with the `maintainer` access level.

Could you please:
- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/[news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)) repo and track announcements there. The ansible-core folks publish changes related to CI (and not only). So if you later set up testing, you'll be informed in advance about the changes. Otherwise, your CI will get red one day in PRs for unclear reasons.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn).
- We have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). Might be useful to take a look.
- If one day you want to see the collection to the ansible community package, I would recommend to take a look at the [Collection checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md) (it's a short version of the [Collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)). Taking it in consideration at the development stage will potentially make the inclusion process easier for maintainers and reviewers.
- Share the above with future maintainers.
- Also the repo was added to Zuul. If you have `community/sonic` namespace on Galaxy created, when Zuul will see a tag, it'll automatically publish the release on Galaxy.

I'll close the issue. If there are any questions, feel free to ask here or on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix) (andersson007_). There's also info on how to create a channel for your community.
Thanks!
