### ISSUE TITLE
repo: ibm.storage_virtualize

### ISSUE THREAD

**Issue by Shilpi-J** [ansible-collections/overview#226]
##### SUMMARY
We want to rename our existing IBM Spectrum virtualize collection to IBM Storage Virtualize.
So, we need to create a new repo with name - ibm.storage_virtualize

##### Name of collection
ibm.storage_virtualize

##### GitHub maintainers

Shilpi Jain(@Shilpi-J)  
Access level: admin

akpande-ibm
Access level: Maintainer

**Comment by Andersson007** [comment]
@Shilpi-J 

- Created https://github.com/ansible-collections/ibm.storage_virtualize.
- Added you as its admin and the person as maintainer (please check your mailboxes for the invites).
- There are GitHub action workflow templates in the `.github/workflows/` directory that you can use to set up CI in the collection.
- Created a [PR](https://github.com/ansible/zuul-config/pull/512) to add the collection to Zuul auto-publishing on Galaxy when it sees tags. It's a very useful feature but if you don't need it, let me know.

Could you please:
- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers) repo and track announcements there. The ansible-core developers publish changes related to CI (and not only). So if you later set up CI, you'll be informed in advance about the changes to be done. Otherwise, the CI will unexpectedly get red one day.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn). Feel free leverage it to announce releases of your collection or anything else that needs community's attention.
- Also we have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). It contains links to releasing guidelines and other useful information. Any feedback will be much appreciated.

Thanks!

**Comment by Shilpi-J** [comment]
Thanks a ton @Andersson007 for the quick resolution ! 

- will set GHA
- I am not aware of this Zuul auto-publishing on Galaxy. I will explore about it and will let you know 

Stay safe !

Thanks

**Comment by Andersson007** [comment]
>I am not aware of this Zuul auto-publishing on Galaxy. I will explore about it and will let you know

@Shilpi-J sure, you're welcome! i'll close the issue then. Feel free to re-open if needed. Thanks
